2019-11-28 12:24:30,665 ERROR: Exception on / [GET] [in /home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/zordo/micro_blog/app/routes.py", line 32, in index
    return render_template('index.html',title ='Home Page', posts= posts, form= form )
NameError: name 'form' is not defined
2019-11-28 12:25:52,399 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-11-28 12:26:00,124 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-11-28 12:26:01,653 ERROR: Exception on / [GET] [in /home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/zordo/micro_blog/app/routes.py", line 21, in index
    posts = g.user.followed_posts().all()
NameError: name 'g' is not defined
2019-11-28 12:26:34,757 ERROR: Exception on /index [GET] [in /home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/zordo/micro_blog/app/routes.py", line 21, in index
NameError: name 'g' is not defined
2019-11-28 12:26:58,680 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-11-28 12:26:59,918 ERROR: Exception on / [GET] [in /home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zordo/micro_blog/venv_f/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/zordo/micro_blog/app/routes.py", line 19, in index
    posts = posts,
NameError: name 'posts' is not defined
2019-11-28 12:27:35,763 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-12-02 11:17:21,035 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-12-02 11:32:16,256 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-12-02 11:35:04,768 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-12-02 11:46:07,767 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-12-02 11:52:55,861 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
2019-12-02 11:55:07,410 INFO: Microblog startup [in /home/zordo/micro_blog/app/__init__.py:47]
